export const dashboardData = [
  {
    id: 1,
    type: "SocialMedia",
    socialName: "facebook",
    icon: "../../images/icon-facebook.svg",
    user: "@user123",
    followers: 2332,
    subtitle: "Followers",
  },
  {
    id: 2,
    type: "SocialMedia",
    socialName: "twitter",
    icon: "../../images/icon-twitter.svg",
    user: "@user123",
    followers: 4512,
    subtitle: "Followers",
  },
  {
    id: 3,
    type: "SocialMedia",
    socialName: "instagram",
    icon: "../../images/icon-instagram.svg",
    user: "@user123",
    followers: 18744,
    subtitle: "Followers",
  },
  {
    id: 4,
    type: "SocialMedia",
    socialName: "youtube",
    icon: "../../images/icon-youtube.svg",
    user: "@user123",
    followers: 6144,
    subtitle: "Followers",
  },
];
